== Setup Workspace

Simple Spring Boot app deployment on Minikube

==== Install apps

- VirtualBox:
https://www.virtualbox.org/wiki/Downloads
- Docker:
https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows
- Minikube:
https://storage.googleapis.com/minikube/releases/latest/minikube-windows-amd64.exe
- Kubectl:
https://kubernetes.io/docs/tasks/tools/install-kubectl/

==== Start Minikube 

In Powershell/cmd (Run as Administrator):

	minikube start --kubernetes-version="v1.8.0" --vm-driver="virtualbox" --memory=4096 --cpus=4 --disk-size=30g --v=7 --alsologtostderr

	& minikube docker-env | Invoke-Expression
	
==== Create a Spring Boot app

Generate new apps using the boot starter. Go to https://start.spring.io/ and choose Web, Actuator dependencies
Unzip the project and then:

----
	cd rest1
	mvnw install
	mkdir docker
	cp .\target\rest1-0.0.1-SNAPSHOT.jar docker/
	cp ..\sample-dockerfile.txt .\docker\Dockerfile
----

Create the docker image

----
	docker build docker/
	docker images
	docker tag <IMAGE_ID> rest1:v.0.1	
----

Create resurces in kubernetes

----
	kubectl apply -f ..\k8s\
----

List all the pods

	kubectl get pods

We can see a pod running

----
NAME                    READY     STATUS    RESTARTS   AGE
rest1-84cc5b858-mrgdd   1/1       Running   0          13m
----

List the services

	kubectl get svc

rest1 has type NodePort
----
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP          7d
rest1        NodePort    10.0.0.108   <none>        8080:31895/TCP   18h
----

Use minikube to expose the rest1 service. You can also pass the --url argument to get the external URL

	minikube service rest1

Print the deployment/service configuration
	
	kubectl get deploy/rest1 -o yaml
	kubectl get svc/rest1 -o yaml
	