apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rest1
    spec:
      containers:
      - name: rest1-app
        image: rest1:v.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: JAVA_TOOL_OPTIONS
          value: " -Xmx512m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /info
            port: web
        livenessProbe:
          httpGet:
            path: /health
            port: web
          initialDelaySeconds: 180

